### ISSUE TITLE
[BUG/ISSUE] MAPL needs several dirty fixes (changing $VPATH, $CPATH) to compile 

### ISSUE THREAD

**Issue by JiaweiZhuang** [geoschem/gchp_legacy#17]
This is just to document several dirty fixes to get around MAPL compile error. I originally thought that they are only needed for gfortran; but it turns that ifort needs exactly the same fixes (tested on Ubuntu 16.04/18.04). No idea why such fixes are not needed on Odyssey. 

```bash
export GC_CODE_DIR=$HOME/tutorial/Code.GCHP  # change this as needed

# --- Fixes for Makefile ---
# Dependencies files *.d in MAPL are messed up in that
# 1. It directly specifies library headers like mpi.h as dependency, which should have been handled by MPI wrapper like mpicc.
# 2. It cannot find *.mod files that are in another directory.
# VPATH allows makefile to search additional directories, although is not a good practice.
# This prevents the error "No rule to make target"
export VPATH=/usr/include/x86_64-linux-gnu:$VPATH # sys/resource.h
export VPATH=$GC_CODE_DIR/GCHP/Shared/MAPL_Base:$VPATH # mapl_*.mod
export VPATH=$GC_CODE_DIR/GCHP/ESMF/Linux/mod:$VPATH # esmf.mod

# --- Fixed for header files ("#include <xxx.h>" statement) ---
# This prevents the error "cannot find..."
export CPATH=$GC_CODE_DIR/GCHP/Shared/MAPL_Base:$CPATH # MAPL_Generic.h
export CPATH=$GC_CODE_DIR/GCHP/Shared/GFDL_fms/shared/include:$CPATH # fms_platform.h

# --- Fixes for module files ("USE xxx" statement) ---
# zonal.f is looking for mapl_constantsmod.mod in its own directory. Even /usr/include/ is not searched
ln -sf $GC_CODE_DIR/GCHP/Shared/MAPL_Base/mapl_constantsmod.mod $GC_CODE_DIR/GCHP/Shared/GEOS_Util/plots/
```

Maybe the new MAPL will handle these better...

**Comment by JiaweiZhuang** [comment]
Those fixes are not needed at all on NASA Pleiades (uses SUSE Linux Enterprise Server 12). Compiles & runs smoothly after loading default modules and setting basic environment variables. Probably not surprising that NASA software works well on NASA computers :)

**Comment by lizziel** [comment]
Very interesting. Once the new MAPL is up and running, if these fixes are still needed in some cases we can add them in. I assume using the fixes with Odyssey/Pleiades also works even though they aren’t needed. True?

--
Lizzie Lundgren
Scientific Programmer
GEOS-Chem Support Team
geos-chem-support@as.harvard.edu<mailto:geos-chem-support@as.harvard.edu>
http://wiki.geos-chem.org/GEOS-Chem_Support_Team

Please direct all GEOS-Chem support issues to the entire GEOS-Chem Support Team
at geos-chem-support@as.harvard.edu<mailto:geos-chem-support@as.harvard.edu>. This will allow us to serve you better.

**Comment by JiaweiZhuang** [comment]
Just successfully compiled on CentOS 7 without all those fixes (on AWS, not Odyssey). Seems like an Ubuntu-only problem...

**Comment by lizziel** [comment]
Good to know. Thanks for reporting this. If you would like to test out compilation on Ubuntu with the new version of MAPL use GCHP branch MAPL_integration. I am curious about whether the fixes you had to apply before are still needed. If they are I can feed this back to GMAO in the near future.

________________________________

**Comment by lizziel** [comment]
@JiaweiZhuang Update to my last comment: To test out compilation on Ubuntu use GCHP branch MAPL_v1.0.0. Let us know if the MAPL dirty fixes for compilation on ubuntu are still required for the new version. If yes, I will discuss with GMAO. If no, I will close out this issue.

**Comment by JiaweiZhuang** [comment]
> To test out compilation on Ubuntu use GCHP branch MAPL_v1.0.0.

Thanks! Which version/branch of GC-classic code should I use to match the `MAPL_v1.0.0` branch?

**Comment by lizziel** [comment]
12.2.0.

--
Lizzie Lundgren
Senior Scientific Programmer
GEOS-Chem Support Team
geos-chem-support@as.harvard.edu<mailto:geos-chem-support@as.harvard.edu>
http://wiki.geos-chem.org/GEOS-Chem_Support_Team

Please direct all GEOS-Chem support issues to the entire GEOS-Chem Support Team
at geos-chem-support@as.harvard.edu<mailto:geos-chem-support@as.harvard.edu>. This will allow us to serve you better.

**Comment by lizziel** [comment]
@JiaweiZhuang What is the status of your planned test? The information I gave you is now outdated and dev/12.5.0 should be used instead, soon to be master.

**Comment by JiaweiZhuang** [comment]
OK I will test 12.5.0 instead.

**Comment by JiaweiZhuang** [comment]
Exact same problem with 12.3.2 (only on Ubuntu; no issue on CentOS). Will test 12.5.0 after the release.

**Comment by JiaweiZhuang** [comment]
Same problem for GCHP 12.5.0 (tested on Ubuntu). Here are two log files before and after the fix:
- [compile_before_VPATH_fix.log](https://github.com/geoschem/gchp/files/3596739/compile_before_VPATH_fix.log)
- [compile_after_VAPTH_fix.log](https://github.com/geoschem/gchp/files/3596740/compile_after_VAPTH_fix.log)

In the first one you can see errors like:
```
c2c.F90:3:10: fatal error: MAPL_Generic.h: No such file or directory
    3 | #include "MAPL_Generic.h"
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
```

In the second one those errors are gone. Although the compilation still fails due to #37.

**Comment by JiaweiZhuang** [comment]
GCHP 12.5.0 (even on CentOS) requires more `CPATH`/`VPATH` fixes than what's described on the top of this thread.

I've finally successfully compiled GCHP 12.5.0 (with gcc8.3.0 + OpenMPI3 + CentOS). Both the successful build and the failed builds can be reproduced by this Docker environment: https://github.com/JiaweiZhuang/docker_gchp/releases/tag/v0.1.0 (remove some fixes in `Dockerfile` and `gchp.env` to see how it fails).

1. First, the complier cannot find `MAPL_Generic.h` without this fix:
```
export CPATH=$GC_CODE_DIR/GCHP/Shared/MAPL_Base:$CPATH # MAPL_Generic.h
```
this was only needed on Ubuntu; don't know why CentOS also needs this starting 12.5.0.

2. Then, the build still fails at this newly-introduced PFIO module:
```
gmake[9]: *** No rule to make target `pfio_stringintegermapmod.mod', needed by `MAPL_IO.o'.  Stop.
```
Full log: [compile_gchp12.5.0_fail_at_pfio.log](https://github.com/geoschem/gchp/files/3603298/compile_gchp12.5.0_fail_at_pfio.log)

This can be fixed by
```
export VPATH=$GC_CODE_DIR/GCHP/Shared/GMAO_pFIO:$VPATH # pfio_stringintegermapmod.mod
```

3. Then, the build still fails at
```
gmake[8]: *** No rule to make target `m_set_eta.mod', needed by `AdvCore_GridCompMod.o'.  Stop.
```
Full log: [compile_gchp12.5.0_fail_at_finding_eta.log](https://github.com/geoschem/gchp/files/3603305/compile_gchp12.5.0_fail_at_finding_eta.log)

This can be fixed by
```
export VPATH=$GC_CODE_DIR/GCHP/Shared/GMAO_hermes:$VPATH # m_set_eta.mod
```

4. Then, the build still fails at
```
Fatal Error: Can't open module file 'm_set_eta.mod' for reading at (1): No such file or directory
```
Full log: [compile_gchp12.5.0_fail_at_using_eta.log](https://github.com/geoschem/gchp/files/3603307/compile_gchp12.5.0_fail_at_using_eta.log)

This can be fixed by
```
ln -sf $GC_CODE_DIR/GCHP/Shared/GMAO_hermes/m_set_eta.mod $GC_CODE_DIR/GCHP/FVdycoreCubed_GridComp/
```

See this commit for all the above fixes: https://github.com/JiaweiZhuang/docker_gchp/commit/d40b0c46962f3a25eabb3a0907bfaec4bf34d2d5

5. Finally, because of https://github.com/geoschem/gchp/issues/39#issuecomment-530600503, the build still fails at
```
/usr/bin/ld: cannot find -lblas
/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -lGMAO_hermes
```
Full log: [compile_gchp12.5.0_fail_at_blas.log](https://github.com/geoschem/gchp/files/3603312/compile_gchp12.5.0_fail_at_blas.log)

This can be fixed by `yum install -y lapack-devel blas-devel` (https://github.com/JiaweiZhuang/docker_gchp/commit/e3c617dbdc62aa142347d9e57d7fca42a4b7a772)

6. Then we finally got this successful build: [compile_gchp12.5.0_success.log](https://github.com/geoschem/gchp/files/3603326/compile_gchp12.5.0_success.log)

For comparison, GCHP 12.3.2 can be built successfully without any of the above fixes (on CentOS) . Full log: [compile_gchp12.3.2_success.log](https://github.com/geoschem/gchp/files/3603327/compile_gchp12.3.2_success.log)
(However, GCHP 12.3.2 cannot be used with gfortran due to run-time errors like #15; I guess 12.5.0 is supposed to fix those run-time errors.)

**Comment by lizziel** [comment]
I am closing this issue since 13.0.0 will be leaps and bounds beyond 12.3.2 in the MAPL version. We are not updating old MAPL at this point. Issues encountered with MAPL in 13.0.0 should be submitted as new issues.
